### ISSUE TITLE
Implement maximum (bipartite) matchings

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#155]
https://en.wikipedia.org/wiki/Matching_(graph_theory)

**Comment by reiniscirpons** [comment]
I am currently working on this. Since matching is something that only makes sense for an undirected graph, I will only implement methods for symmetric digraphs.

Currently am implementing the [Blossom algorithm](https://en.wikipedia.org/wiki/Blossom_algorithm) which finds a maximum matching in `O(E*V^2)` time, where `V` is the number of vertices and `E` is number of edges.

Afterwards might upgrade to the Micali-Vazirani algorithm which runs in `O(E*sqrt(V))` time and is the most efficient known algorithm for the problem. Currently thinking of using notes from [this article](https://arxiv.org/abs/1210.4594).

**Comment by james-d-mitchell** [comment]
Resolved in v1.2.0
