### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-packages/Digraphs#188]
Is there a possibility to set colors of nodes (e.g., using `SetDigraphVertexLabels`) which are then used by `DotVertexLabelledDigraph`?

**Comment by wilfwilson** [comment]
I'm not sure I understand the question. It is indeed possible to set the labels (or, as some people say, colours) of the vertices using `SetDigraphVertexLabels`, and then `DotVertexLabelledDigraph` attempts to display the vertices of the digraph with these labels. For example, this code:
```
gap> gr := CycleDigraph(5);
<digraph with 5 vertices, 5 edges>
gap> SetDigraphVertexLabels(gr, List(AllSmallGroups(8), StructureDescription));
gap> Splash(DotVertexLabelledDigraph(gr));
```
Produces:
![labels](https://user-images.githubusercontent.com/8956868/54992630-0a803400-4fc0-11e9-91eb-9b0ebf9bed06.jpg)
Although not pretty, this does make an attempt at displaying the labels. Does that answer your question?

Or, are you perhaps thinking specifically about the *colours*, as in red, green, blue etc? Is your question: is there a way for me to assign actual *colours* to a digraph (such as red, yellow, brown, green, ...), such that some `Dot(something)Digraph` will render the vertices so that they are highlighted/shaded with their corresponding colour (and still labelled with the correct vertex number, such as1, 2, 3, ... etc)? If you question is this, then the answer is that we don't currently have such functionality.

**Comment by wilfwilson** [comment]
Note that issue https://github.com/gap-packages/Digraphs/issues/170 also suggests/requests functionality for producing images that use actual colours (red/green/...) for vertices and edges.

**Comment by mohamed-barakat** [comment]
Yes, I really mean colors (red/green/...). Since this issue duplicated I will close it.
