### ISSUE TITLE
Implement NrSpanningTree's

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Digraphs#197]
For an undirected simple graph, the number of spanning trees can be found by computing the eigenvalues of the so-called *Laplacian matrix* (the difference of the matrix with the degrees of the vertices on the diagonal and the adjacency matrix). See https://en.wikipedia.org/wiki/Kirchhoff%27s_theorem

I suppose this would necessitate implementing:

* `LaplacianMatrix`
* `DegreeMatrix`
* `NrSpanningTrees`

**Comment by reiniscirpons** [comment]
Im working on this, but I have a question: How to handle directed graphs? Kirchoff's theorem as stated in wikipedia only makes sense for undirected graphs.  Here are some options:

1. One way would be to require that digraph is undirected before computing NrSpanningTrees. 

2. Another would be to treat the directed graph as undirected (i.e. by adding missing edges) and then do the spanning tree calculation. 

3. Finally, it is also possible to directly generalize Kirchoff's theorem s to directed graphs, see http://www.math.uchicago.edu/~may/VIGRE/VIGRE2010/REUPapers/Margoliash.pdf. 

To summarize the paper above: Define a _sink_ to be a vertex of a digraph that is reachable from any other vertex of the digraph. Let the _outdegree Laplacian matrix_ be the Laplacian matrix obtained by using the outdegrees of the digraph. A _reverse arborescence_ is a digraph in which there is a unique path from any vertex to a sink. 

For a given digraph _G_ and sink _s_, the determinant of the outdegree Laplacian matrix  with the row and column of _s_ removed (which is the same as the eigenvalue computation) corresponds to the number of reverse arborescences spanning G with sink _s_. 

A similar theorem using the indegree Laplacian instead gives the number of spanning arborescences.

When _G_ is undirected, the number of spanning trees, spanning arborescences and spanning reverse arborescences coincides.

I am unsure which way is best to proceed with and whether its worth implementing 3., especially since you would need to implement a bunch more functions with limited utility.

**Comment by wilfwilson** [comment]
I would vote for number 1.

**Comment by wilfwilson** [comment]
Resolved in v1.0.0.
