### ISSUE TITLE
HomomorphismDigraphsFinder: Letting the hook function stop the search for homomorphisms

### ISSUE THREAD

**Issue by MTWhyte** [gap-packages/Digraphs#203]
It would be useful if the hook function in `HomomorphismDigraphsFinder` could be equipped with a boolean which would allow the search for homomorphisms to be stopped.

This would make searching for a homomorphism with a property not included in the other arguments of `HomomorphismDigraphsFinder` more efficient, as the process could be stopped by the user written hook function when a desired homomorphism has been found.

**Comment by james-d-mitchell** [comment]
I support this, and I don't think it'll be hard to implement. Good suggestion @MTWhyte

**Comment by ChrisJefferson** [comment]
Random GAP fact, in case you don't know it: If you call a function with `CallFuncListWrap`, then you the return value is put in a one argument list, or you get an empty list if the function didn't return a value.

I mention this just because it makes it possible to let people now return a value, while still supporting any old implementations that returned nothing.

**Comment by james-d-mitchell** [comment]
Thanks @ChrisJefferson this may indeed be helpful when resolving this.

**Comment by james-d-mitchell** [comment]
Resolved by PR #210

**Comment by wilfwilson** [comment]
Resolved in v1.0.0.
