### ISSUE TITLE
no 1st choice method found for `DigraphAddVertices' on 3 arguments 

### ISSUE THREAD

**Issue by nzidaric** [gap-packages/Digraphs#264]
Hi , i had to do the following workaround to keep my code working
 ( always used with m = Length(labels)  anyway )

InstallOtherMethod(DigraphAddVertices, "for a digraph - ignore m",  
[IsDigraph, IsInt, IsList], function(digraph, m , labels)
  return DigraphAddVertices(digraph, labels);
end);

thanks,
brn

**Comment by wilfwilson** [comment]
Thanks @nzidaric, I’m sorry that the new version broke your code.

My best guess is that someone realised (as your code shows above!) that the middle argument is somewhat redundant in the three-argument case, and removed it, leaving just the two-argument version that your code snippet delegates to. I wasn’t aware that this had been happened, which is why I didn’t mention it in the `CHANGELOG`.

I’ll be happy to add back in the three-argument version to help maintain backwards compatibility with your code, without needing the `InstallOtherMethod` that you showed above.

In the long term, I would recommend that you migrate your code to use the two-argument version, if possible, simply because it’s kind of neater. But there’s no rush for that.

Hopefully I can release a new version on Sunday.

**Comment by wilfwilson** [comment]
The 3-argument `DigraphAddVertices` method is back in version 1.0.1, which I just released 🙂
